services:

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: eshop
      POSTGRES_PASSWORD: eshop
    ports:
      - "5432:5432"
    healthcheck: 
      test: ["CMD", "pg_isready", "-U", "eshop"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  catalog-api:
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      ConnectionStrings__catalogdb: Host=postgres;Port=5432;database=catalogdb;Username=eshop;Password=eshop
      ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672

      Aspire__RabbitMQ__Client__ConnectionString: amqp://guest:guest@rabbitmq:5672
      Aspire__RabbitMQ__Client__DisableHealthCheck: "false"

  basket-api:
    build:
      context: .
      dockerfile: src/Basket.API/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - redis
      - rabbitmq
    environment:
      ConnectionStrings__Redis: redis:6379
      ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672

  identity-api:
    build:
      context: .
      dockerfile: src/Identity.API/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__identitydb: Host=postgres;Port=5432;database=identitydb;Username=eshop;Password=eshop

  ordering-api:
    build:
      context: .
      dockerfile: src/Ordering.API/Dockerfile
    ports:
      - "5004:80"
    depends_on:
      - postgres
      - rabbitmq
      - identity-api
    environment:
      ConnectionStrings__orderingdb: Host=postgres;Port=5432;database=orderingdb;Username=eshop;Password=eshop
      ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672
      IdentityUrl: http://identity-api
      CallBackUrl: http://localhost:8080/signin-oidc
      services__identity-api__http__0: http://identity-api
    
  order-processor:
    build:
      context: .
      dockerfile: src/OrderProcessor/Dockerfile
    depends_on:
      - rabbitmq
      - ordering-api
    environment:
      ConneectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672
      services__ordering-api__http__0: http://ordering-api 

  webapp:
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - catalog-api
      - basket-api
      - identity-api
    #  - ordering-api
    environment:
      IdentityUrl: http://identity-api
      CatalogUrl: http://catalog-api
      BasketUrl: http://basket-api
      CallbackUrl: http://localhost:8080/signin-oidc
      ApiSettings__CatalogUrl: http://catalog-api
      ApiSettings__BasketUrl: http://basket-api
      ApiSettings__IdentityUrl: http://identity-api

      services__catalog-api__http__0: http://catalog-api
      services__identity-api__http__0: http://identity-api

      ASPNETCORE_HTTPS_PORT:
      DOTNET_HTTP_PORTS: 80

networks:
  default:
    driver: bridge    

